import google.generativeai as genai
from google.generativeai import types
import numpy as np
from numpy.linalg import norm
from typing import List, Optional
from .base_embedder import Embedder 
import os

class GeminiEmbedder(Embedder):
    """
    Embedder for the Google Gemini API's text embedding models.

    Uses the specified Gemini embedding model (e.g., "gemini-embedding-001")
    to generate text embeddings. Supports specifying task type and desired
    output dimensionality.

    Requires GOOGLE_API_KEY to be set in environment variables, or passed
    directly during initialization.

    Attributes:
        model_name (str): The name of the Gemini embedding model to use.
        _task_type (str): The task type for which embeddings are optimized.
        _output_dimensionality (int): The desired dimension of the output embeddings.
    """

    # Supported task types based on Gemini API documentation
    SUPPORTED_TASK_TYPES = {
        "SEMANTIC_SIMILARITY", "CLASSIFICATION", "CLUSTERING",
        "RETRIEVAL_DOCUMENT", "RETRIEVAL_QUERY", "CODE_RETRIEVAL_QUERY",
        "QUESTION_ANSWERING", "FACT_VERIFICATION"
    }

    # Recommended defaults by Google for gemini-embedding-001
    DEFAULT_MODEL_NAME = "gemini-embedding-001"
    DEFAULT_TASK_TYPE = "SEMANTIC_SIMILARITY"
    # 768 is a recommended dimension for efficiency, 3072 is the default full dimension
    DEFAULT_OUTPUT_DIMENSIONALITY = 768

    def __init__(
        self,
        model_name: str = DEFAULT_MODEL_NAME,
        task_type: str = DEFAULT_TASK_TYPE,
        output_dimensionality: int = DEFAULT_OUTPUT_DIMENSIONALITY,
        api_key: Optional[str] = None,
        **kwargs
    ):
        """
        Initializes the GeminiEmbedder.

        Args:
            model_name (str): The specific Gemini embedding model to use.
                              Defaults to "gemini-embedding-001".
            task_type (str): The task for which the embeddings are intended.
                             Must be one of SUPPORTED_TASK_TYPES.
                             Defaults to "SEMANTIC_SIMILARITY".
            output_dimensionality (int): The desired length of the embedding vector.
                                         Must be between 128 and 3072.
                                         Recommended values are 768, 1536, or 3072.
                                         Defaults to 768.
            api_key (Optional[str]): Your Google Cloud API key. If not provided,
                                     the embedder will look for 'GOOGLE_API_KEY'
                                     in environment variables.
            **kwargs: Additional keyword arguments for the base Embedder class.

        Raises:
            ValueError: If an unsupported task_type or invalid output_dimensionality
                        is provided, or if no API key is found.
            RuntimeError: If there's an issue initializing the Gemini API client.
        """
        super().__init__(model_name, **kwargs)

        if task_type not in self.SUPPORTED_TASK_TYPES:
            raise ValueError(f"Unsupported task_type: '{task_type}'. "
                             f"Must be one of {sorted(list(self.SUPPORTED_TASK_TYPES))}")
        self._task_type = task_type

        # Validate output_dimensionality based on documentation (128 - 3072)
        # The documentation suggests 768, 1536, 3072 are recommended.
        if not (128 <= output_dimensionality <= 3072):
            raise ValueError(f"Output dimensionality {output_dimensionality} is out of "
                             "the supported range [128, 3072]. "
                             "Recommended values: 768, 1536, 3072.")
        self._output_dimensionality = output_dimensionality

        # Configure the Gemini API client
        if api_key:
            genai.configure(api_key=api_key)
        else:
            if "GOOGLE_API_KEY" not in os.environ:
                raise ValueError(
                    "GOOGLE_API_KEY environment variable not set and no api_key provided. "
                    "Please set the environment variable or pass api_key to the constructor."
                )
            # genai.configure() without an api_key argument will use the env var automatically
            genai.configure() 
        
        # Initialize the client. This will use the configured API key.
        try:
            self._client = genai.Client()
        except Exception as e:
            raise RuntimeError(f"Failed to initialize Gemini API client: {e}") from e


    @property
    def embedding_dim(self) -> int:
        """
        Returns the dimension of the embeddings generated by this embedder.
        """
        return self._output_dimensionality

    def get_embeddings(self, texts: List[str]) -> np.ndarray:
        """
        Generates embeddings for a list of texts in a batch using the Gemini API.

        Args:
            texts: A list of strings to embed. Empty strings in the list are
                   expected to be handled gracefully by the Gemini API,
                   typically resulting in a zero vector embedding.

        Returns:
            A NumPy array of embeddings. Each row in the array corresponds
            to an input text. If the input list is empty, an empty NumPy array
            is returned.

        Raises:
            RuntimeError: If an error occurs during the API call or embedding processing.
        """
        if not texts:
            return np.array([], dtype=np.float32) # Return empty array for empty input list

        try:
            config = types.EmbedContentConfig(
                task_type=self._task_type,
                output_dimensionality=self._output_dimensionality
            )

            result = self._client.models.embed_content(
                model=self.model_name,
                contents=texts,
                config=config
            )

            # Extract embeddings as numpy arrays
            # Each item in result.embeddings is a types.Embedding object with a .values attribute
            raw_embeddings = [np.array(e.values, dtype=np.float32) for e in result.embeddings]

            # Normalize embeddings if output_dimensionality is not 3072, as per Google's recommendation.
            # The 3072-dimension embeddings are already normalized by the API.
            if self._output_dimensionality != 3072:
                normalized_embeddings = []
                for emb in raw_embeddings:
                    # Check if the norm is effectively zero to avoid division by zero
                    # Use a small epsilon for floating point comparison to handle near-zero vectors
                    current_norm = norm(emb)
                    if current_norm < 1e-6: 
                        normalized_embeddings.append(emb) # Keep as is if it's a zero vector
                    else:
                        normalized_embeddings.append(emb / current_norm)
                return np.array(normalized_embeddings, dtype=np.float32)
            else:
                # For 3072 dimensions, embeddings are already normalized by the API
                return np.array(raw_embeddings, dtype=np.float32)

        except Exception as e:
            # Catch broader exceptions for API failures or unexpected responses
            raise RuntimeError(f"Error generating embeddings with Gemini API: {e}") from e