#!/bin/bash
#SBATCH --job-name=strategy_clustering
#SBATCH --output=slurm_logs/clustering_%A.out
#SBATCH --error=slurm_logs/clustering_%A.err
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=16G        # Note: May need more memory depending on the total size of annotated data
#SBATCH --time=02:00:00

#======================================================================================
#
# SLURM Job Submission Script for Strategy Clustering Analysis
#
# Purpose:
#   This script runs the final analysis step. It aggregates all the annotated
#   route files generated by the 'submit_annotation.sh' script and then
#   executes 'clustering.py' to perform strategy clustering, producing a
#   single summary output file.
#
# Prerequisites:
#   - The 'submit_annotation.sh' job array must have completed successfully.
#   - A Python environment (e.g., Conda) with all necessary packages installed.
#   - The 'clustering.py' script.
#
# Usage:
#   1. Configure the variables in the "USER CONFIGURATION" section below.
#   2. Adjust the SBATCH resource directives (e.g., --mem, --time) as needed.
#   3. Submit the script to SLURM: sbatch submit_clustering.sh
#
#======================================================================================

# --- USER CONFIGURATION ---
# Please modify the following paths and settings to match your environment.

# 1. Project Directory (base path for your project)
PROJECT_DIR="/path/to/your/project"

# 2. Input Directory: Must be the SAME as ANNOTATED_ROUTES_DIR from the annotation script.
#    This directory contains all the 'annotated_smiles*.json' files.
ANNOTATED_ROUTES_DIR="${PROJECT_DIR}/data/annotated_routes"

# 3. Output Directory: Where the final analysis results will be saved.
RESULTS_DIR="${PROJECT_DIR}/results"

# 4. Output Filename: The name of the final JSON file containing the analysis.
FINAL_ANALYSIS_FILE="${RESULTS_DIR}/strategy_clustering_analysis.json"

# 5. Code Directory: Path to the source code of the strategy functions.
#    This is used by clustering.py to extract docstrings for documentation.
STRATEGY_FUNCTIONS_DIR="${PROJECT_DIR}/src/strategy_functions"

# 6. Conda Environment: Name of the Conda environment to activate - you should use
CONDA_ENV_NAME="your-conda-env-name"

# --- END OF USER CONFIGURATION ---


# --- Script Setup ---
set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error when substituting.

echo "================================================="
echo "SLURM Job ID: ${SLURM_JOB_ID}"
echo "================================================="

echo "Creating output and log directories if they do not exist..."
mkdir -p "${RESULTS_DIR}"
mkdir -p "slurm_logs"


# --- Environment Activation ---
echo "Loading Conda environment: ${CONDA_ENV_NAME}"
# IMPORTANT: The path to 'conda.sh' may vary.
# Common locations: ~/miniconda3/etc/profile.d/conda.sh or ~/anaconda3/etc/profile.d/conda.sh
source "/path/to/your/miniconda3/etc/profile.d/conda.sh"
conda activate "${CONDA_ENV_NAME}"


# --- Execute Clustering Script ---
echo "--- Starting Strategy Clustering Analysis ---"
echo "Input Directory:  ${ANNOTATED_ROUTES_DIR}"
echo "Output File:      ${FINAL_ANALYSIS_FILE}"
echo "Code Source Dir:  ${STRATEGY_FUNCTIONS_DIR}"

python clustering.py \
    --input-dir "${ANNOTATED_ROUTES_DIR}" \
    --output "${FINAL_ANALYSIS_FILE}" \
    --code-dir "${STRATEGY_FUNCTIONS_DIR}"

echo "--- Strategy Clustering finished successfully. ---"
echo "Results saved to: ${FINAL_ANALYSIS_FILE}"